### ISSUE TITLE
Optimize the analyse process

### ISSUE THREAD

**Issue by cchampet** [mikrosimage/loudness_validator#6]
These following points can be a started point:

Why did it divide by 5? Could the buffer be larger than that?
https://github.com/mikrosimage/loudness_validator/blob/develop/src/tool/common/ProcessFile.hpp#L12

Could this loop of affectations be avoided?
https://github.com/mikrosimage/loudness_validator/blob/develop/src/tool/common/ProcessFile.hpp#L31

Could this call be multi threaded?
https://github.com/mikrosimage/loudness_validator/blob/develop/src/loudnessAnalyser/LoudnessAnalyser.cpp#L35

@ChristopheLorenz 
@MarcAntoine-Arnaud 
Do you have any idea of how to improve performances of analyse process?

**Comment by MarcAntoine-Arnaud** [comment]
Good questions :+1: 
For the buffer, yes it can be more larger than sample rate / 5. I think it's a error to divide per 5 (maybe for tests on multichannels ... ). It can optimize a little the process, providing less calls. But not very significant.

For the loop, it was usefull to reorganise samples per channels.
Readed buffer was interleaved (R, C, L, Sr, Sl, LFE) and require to have a buffer per channel.
Maybe it can be optimised using SIMD instructions, need to be investigated.

The process is hard to multithreaded because we use some circular buffers internaly. It requires some modifications on internal process to enable the threading of measurement.

Do you have some benchmark results ?
If I remembers measurement was around 8 times more rapidly than the program duration. Is it that ?

**Comment by MarcAntoine-Arnaud** [comment]
I think it can be great to add SIMD instructions here:
https://github.com/mikrosimage/loudness_validator/blob/develop/src/loudnessAnalyser/Filter.cpp#L81
But it may require to pass not a single sample, an array of sample can be better.

**Comment by cchampet** [comment]
I've done some tests with short and long programs:
__Long__
Wrapper wav
02:01:00.03, bitrate: 1536 kb/s
Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s
=> 65m15.768s to analyse

__Short__
Wrapper wav
00:00:20.00, bitrate: 4608 kb/s
Audio: pcm_s16le, 48000 Hz, 5.1, s16, 4608 kb/s
=> 27.049s to analyse

**Comment by cchampet** [comment]
I think we have a situation here:
![kcachegrind](https://cloud.githubusercontent.com/assets/2589095/8869928/d82e0e66-31e9-11e5-8328-a99f063020a6.png)
